version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10

python:
    install:
        - method: pip
          path: .
          extra_requirements:
            - docs

conda:
  environment: environment.yml

sphinx:
    builder: html
    fail_on_warning: false
