version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10

conda:
  environment: environment.yml

python:
    install:
        - method: pip
          path: .
          extra_requirements:
            - docs

sphinx:
    configuration: docs/source/conf.py
    fail_on_warning: false
