[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = 'aiida-phonopy'
dynamic = ['version']
description = 'The official AiiDA plugin for Phonopy'
authors = [
    {name = 'Lorenzo Bastonero', email = 'bastonero.lorenzo@gmail.com'}
]
readme = 'README.md'
license = {file = 'LICENSE.txt'}
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Framework :: AiiDA',
    'License :: OSI Approved :: MIT License',
    'Operating System :: POSIX :: Linux',
    'Operating System :: MacOS :: MacOS X',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Topic :: Scientific/Engineering :: Physics',
    'Topic :: Scientific/Engineering :: Chemistry',
]
keywords = ['aiida', 'phonopy', 'workflows']
requires-python = '>=3.10'
dependencies = [
    "aiida-core~=2.8",
    "phonopy~=4.0",
    "aiida-pythonjob~=0.5",
    "seekpath",
]

[project.urls]
Source = "https://github.com/aiida-phonopy/aiida-phonopy"

[project.optional-dependencies]
pre-commit = [
    'pre-commit>=4.3.0',
]
tests = [
    'ase',
    'pgtest~=1.3',
    'pytest~=8.4',
    'coverage[toml]',
    'pytest-cov',
    'pytest-regressions~=2.8',
    'pytest-timeout',
]
docs = [
    'myst-nb~=1.0',
    'jupytext>=1.11.2,<1.15.0',
    'sphinx~=6.2.1',
    'sphinx-copybutton~=0.5.2',
    'sphinx-book-theme~=1.0.1',
    'sphinx-click~=4.4.0',
    'sphinx-design~=0.4.1',
    'sphinxcontrib-details-directive~=0.1.0',
    'sphinx-autoapi~=3.0.0',
    'myst-parser~=3.0.0',
    'sphinx-togglebutton',
]

[dependency-groups]
dev = [
  "aiida-phonopy[docs,tests,pre-commit]",
]

[project.entry-points.'aiida.data']
'phonopy.raw' = 'aiida_phonopy.data.raw:RawData'
'phonopy.preprocess' = 'aiida_phonopy.data.preprocess:PreProcessData'
'phonopy.phonopy' = 'aiida_phonopy.data.phonopy:PhonopyData'
'phonopy.force_constants' = 'aiida_phonopy.data.force_constants:ForceConstantsData'

[project.entry-points.'aiida.calculations']
'phonopy.phonopy' = 'aiida_phonopy.calculations.phonopy:PhonopyCalculation'

[project.entry-points.'aiida.parsers']
'phonopy.phonopy' = 'aiida_phonopy.parsers.phonopy:PhonopyParser'

[project.entry-points.'aiida.workflows']
'phonopy.phonopy' = 'aiida_phonopy.workflows.phonopy:PhonopyWorkChain'
'phonopy.ase' = 'aiida_phonopy.workflows.ase:PhonopyAseWorkChain'

[tool.hatch.build.targets.wheel]
packages = ['src/aiida_phonopy']

[tool.hatch.build.targets.sdist]
exclude = [
  'docs/',
  'examples/',
  'tests/',
]

[tool.hatch.version]
path = 'src/aiida_phonopy/__init__.py'

[tool.hatch.envs.default]
installer = 'uv'

[tool.hatch.envs.pre-commit]
features = ["pre-commit"]
scripts.install = 'pre-commit install'
scripts.run = 'pre-commit run {args}'

[tool.hatch.envs.hatch-test]
features = ["tests"]
randomize = false
parallel = false
run = "pytest {args}"

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.10", "3.11", "3.12", "3.13", "3.14"]

[tool.hatch.envs.docs]
features = ["docs"]
scripts.clean = 'make -C docs clean'
scripts.build = 'make -C docs html'
scripts.view = 'make -C docs view'

[tool.ruff]
line-length = 120
extend-exclude = ['*.ipynb']
lint.ignore = [
    "ARG002",  # https://docs.astral.sh/ruff/rules/unused-method-argument/
    "ARG004",  # https://docs.astral.sh/ruff/rules/unused-static-method-argument/
    "B028",    # https://docs.astral.sh/ruff/rules/no-explicit-stacklevel/
    "BLE001",  # https://docs.astral.sh/ruff/rules/blind-except/
    "EM101",   # https://docs.astral.sh/ruff/rules/raw-string-in-exception/
    "EM102",   # https://docs.astral.sh/ruff/rules/f-string-in-exception/
    "EXE001",  # https://docs.astral.sh/ruff/rules/shebang-not-executable/
    "FA100",   # https://docs.astral.sh/ruff/rules/future-rewritable-type-annotation/
    "FBT001",  # https://docs.astral.sh/ruff/rules/boolean-type-hint-positional-argument/
    "FBT002",  # https://docs.astral.sh/ruff/rules/boolean-default-value-positional-argument/
    "G004",    # https://docs.astral.sh/ruff/rules/logging-f-string/
    "N805",    # https://docs.astral.sh/ruff/rules/invalid-first-argument-name-for-method/
    "PERF401", # https://docs.astral.sh/ruff/rules/manual-list-comprehension/
    "PLR2004", # https://docs.astral.sh/ruff/rules/magic-value-comparison/
    "RUF005",  # https://docs.astral.sh/ruff/rules/collection-literal-concatenation/
    "RUF012",  # https://docs.astral.sh/ruff/rules/mutable-class-default/
    "RET503",  # https://docs.astral.sh/ruff/rules/implicit-return/
    "S110",    # https://docs.astral.sh/ruff/rules/try-except-pass/
    "S318",    # https://docs.astral.sh/ruff/rules/suspicious-xml-mini-dom-usage/
    "S314",    # https://docs.astral.sh/ruff/rules/suspicious-xml-element-tree-usage/
    "TID252",  # https://docs.astral.sh/ruff/rules/relative-imports/
    "TRY004",  # https://docs.astral.sh/ruff/rules/type-check-without-type-error/
    "TRY003",  # https://docs.astral.sh/ruff/rules/raise-vanilla-args/
    "TRY301",  # https://docs.astral.sh/ruff/rules/raise-within-try/
]
[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "INP001",  # https://docs.astral.sh/ruff/rules/implicit-namespace-package/
    "PT009",   # https://docs.astral.sh/ruff/rules/pytest-unittest-assertion/
    "PT011",   # https://docs.astral.sh/ruff/rules/pytest-raises-too-broad/
    "PT027",   # https://docs.astral.sh/ruff/rules/pytest-unittest-raises-assertion/
    "S101",    # https://docs.astral.sh/ruff/rules/assert/
    "SLF001",  # https://docs.astral.sh/ruff/rules/private-member-access/
]
"docs/**/*.py" = ["ALL"]
"examples/**/*.py" = ["ALL"]

[tool.ruff.format]
quote-style = "single"
