name: Publish on PyPI

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'aiida-phonopy/aiida-phonopy' && startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install flit
      run: |
        python -m pip install --upgrade pip
        python -m pip install flit~=3.4

    - name: Build and publish to TestPyPI
      run: |
        flit publish
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD:  ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Build and publish to PyPI
      run: |
        flit publish
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD:  ${{ secrets.PYPI_API_TOKEN }}
